-- MySQL Script generated by MySQL Workbench
-- lun. 28 juin 2021 19:12:49 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Portfolio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Portfolio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Portfolio` DEFAULT CHARACTER SET latin1 ;
USE `Portfolio` ;

-- -----------------------------------------------------
-- Table `Portfolio`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portfolio`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `lastname` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `mail` VARCHAR(45) NOT NULL,
  `status` TINYINT(4) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `Portfolio`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portfolio`.`post` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `text` TEXT NOT NULL,
  `picture` VARCHAR(45) NOT NULL,
  `status` INT(11) NOT NULL,
  `date_creation` DATETIME NOT NULL,
  `date_update` DATETIME NULL DEFAULT NULL,
  `autor_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_user_idx` (`autor_id` ASC) VISIBLE,
  CONSTRAINT `fk_post_user`
    FOREIGN KEY (`autor_id`)
    REFERENCES `Portfolio`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
KEY_BLOCK_SIZE = 1;


-- -----------------------------------------------------
-- Table `Portfolio`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Portfolio`.`comment` (
  `id` INT(11) NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `text` TEXT NOT NULL,
  `status` TINYINT(4) NOT NULL,
  `date_creation` DATETIME NOT NULL,
  `date_update` DATETIME NULL DEFAULT NULL,
  `post_id` INT(11) NOT NULL,
  `autor_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_comment_post1_idx` (`post_id` ASC) VISIBLE,
  INDEX `fk_comment_user1_idx` (`autor_id` ASC) VISIBLE,
  CONSTRAINT `fk_comment_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `Portfolio`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`autor_id`)
    REFERENCES `Portfolio`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
